services:
  - type: web
    name: gmb-tracker
    runtime: python
    runtimeVersion: 3.11.9
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -b 0.0.0.0:$PORT wsgi:app
